name: TomBlock
version: 1.0
main: org.tomdang.TomBlock
author: TomDang
api-version: 26.2

commands:
  setmininglvl:
    description: set the mining level of a player
    aliases:
      mlvl
  getmininglvl:
    description: get the mining level of a player
    aliases:
      mining
  setminingxp:
    description: set the mining xp of a player
    aliases:
      miningxp
  giveminingtool:
    description: give the sender a custom mining tool
  giveweapon:
    description: give the sender a custom weapon
  spawncustommob:
    description: spawn a custom mob at the sender's location
  stats:
    description: returns a customGUI of the sender's stats
  setdefense:
    description: sets the sender's defense stat to the desired double amount
  givecustomarmor:
    description: gives the sender a custom armor from the registry
    aliases:
      givearmor
  heal:
    description: heal the sender for a specified amount
  useenergy:
    description: spends a specified amount of the spender's energy
  recoverenergy:
    description: recovers a specified amount of the spender's energy
  forge:
    description: opens a custom crafting gui
  dialoguechoice:
    description: This is technically available as a player command, but it is intended primarily as the internal target used by clickable messages.
  spawnnmsnpc:
    description: spawn a custom NMS NPC!
  moveactortest:
    description: a test command to move an actor instance
  followtest:
    description: a test command to make an actor instance follow the sender
  actorlook:
    description: tells a npc to look at the command sender