package org.tomdang.critter.progression;
import org.bukkit.Bukkit;import org.tomdang.critter.definition.*;import org.tomdang.critter.journal.*;import org.tomdang.customitemframework.*;import org.tomdang.gameplay.event.*;import org.tomdang.gameplay.event.type.*;import org.tomdang.player.*;import org.tomdang.player.playerdata.PlayerProfileRepository;import org.tomdang.player.skill.*;import java.util.*;import java.util.concurrent.ThreadLocalRandom;
/** Journal, XP, and material consumer of generic critter gameplay events. */
public final class CritterProgressionService implements AutoCloseable{
	private final CritterRegistry definitions;private final CritterJournalService journal;private final PlayerProfileService profiles;private final PlayerProfileRepository repository;private final SkillProgressionService skills;private final SkillProgressPresenter presenter;private final CustomItemRegistry items;private final CustomItemStackFactory stacks;private final List<GameplayEventSubscription> subscriptions=new ArrayList<>();
	public CritterProgressionService(GameplayEventBus events,CritterRegistry definitions,CritterJournalService journal,PlayerProfileService profiles,PlayerProfileRepository repository,SkillProgressionService skills,SkillProgressPresenter presenter,CustomItemRegistry items,CustomItemStackFactory stacks){this.definitions=definitions;this.journal=journal;this.profiles=profiles;this.repository=repository;this.skills=skills;this.presenter=presenter;this.items=items;this.stacks=stacks;subscriptions.add(events.subscribe(CritterObserved.class,event->{definitions.require(event.critterId());journal.observe(event.playerId(),event.critterId());}));subscriptions.add(events.subscribe(CritterCaptured.class,this::captured));}
	private void captured(CritterCaptured event){CritterDefinition definition=definitions.require(event.critterId());journal.hunt(event.playerId(),event.critterId());PlayerProfile profile=profiles.getPlayerProfileFromMap(event.playerId());if(profile==null)return;var result=skills.awardXp(profile,SkillType.HUNTING,definition.rewards().huntingXp());repository.savePlayerProfile(profile);var player=Bukkit.getPlayer(event.playerId());if(player==null)return;presenter.showAward(player,result);for(var entry:definition.rewards().materials().entrySet()){var drop=entry.getValue();if(ThreadLocalRandom.current().nextDouble()>drop.chance())continue;int amount=ThreadLocalRandom.current().nextInt(drop.minimum(),drop.maximum()+1);if(amount==0)continue;var item=items.getCustomItem(entry.getKey());if(item==null)throw new IllegalStateException("Unknown critter reward item "+entry.getKey());var overflow=player.getInventory().addItem(stacks.createCustomItemStack(item,amount));for(var stack:overflow.values())player.getWorld().dropItemNaturally(player.getLocation(),stack);}}
	public void close(){for(int i=subscriptions.size()-1;i>=0;i--)subscriptions.get(i).close();subscriptions.clear();}
}
