package org.tomdang.critter.presentation;
import net.kyori.adventure.text.Component;import net.kyori.adventure.text.format.NamedTextColor;import org.bukkit.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.player.PlayerInteractEntityEvent;import org.bukkit.inventory.ItemStack;import org.tomdang.critter.runtime.*;import org.tomdang.encounter.runtime.*;import java.util.*;import java.util.function.Supplier;
/** Replaceable Glimmerfly prototype: a private glowing item display plus interaction hitbox. */
public final class GlimmerflyEncounterBehavior implements EncounterBehavior,Listener,AutoCloseable{
	private final PluginHandle plugin;private final CritterRuntimeService critters;private final Supplier<EncounterRuntimeService> encounters;private final Map<UUID,View> byHitbox=new HashMap<>();private final Map<UUID,View> byEncounter=new HashMap<>();
	public GlimmerflyEncounterBehavior(org.bukkit.plugin.Plugin plugin,CritterRuntimeService critters,Supplier<EncounterRuntimeService> encounters){this.plugin=new PluginHandle(plugin);this.critters=critters;this.encounters=encounters;Bukkit.getPluginManager().registerEvents(this,plugin);}
	@Override public void start(EncounterRuntimeContext context){Player player=Bukkit.getPlayer(context.session().ownerId());if(player==null)return;spawn(context,player);}
	@Override public void resume(EncounterRuntimeContext context){Player player=Bukkit.getPlayer(context.session().ownerId());if(player!=null&&byEncounter.get(context.session().instanceId())==null)spawn(context,player);}
	@Override public void suspend(EncounterRuntimeContext context){remove(context.session().instanceId());}
	@Override public void complete(EncounterRuntimeContext context){remove(context.session().instanceId());}
	@Override public void fail(EncounterRuntimeContext context,String reason){remove(context.session().instanceId());}
	private void spawn(EncounterRuntimeContext context,Player player){Location location=player.getLocation().clone().add(player.getLocation().getDirection().setY(0).normalize().multiply(4)).add(0,1.4,0);World world=player.getWorld();ItemDisplay display=world.spawn(location,ItemDisplay.class,value->{value.setItemStack(ItemStack.of(Material.GLOWSTONE_DUST));value.setBillboard(Display.Billboard.CENTER);value.setGlowing(true);value.setVisibleByDefault(false);});Interaction hitbox=world.spawn(location,Interaction.class,value->{value.setInteractionWidth(0.8f);value.setInteractionHeight(0.8f);value.setResponsive(true);});for(Player online:Bukkit.getOnlinePlayers())if(!online.equals(player))online.hideEntity(plugin.value,hitbox);player.showEntity(plugin.value,display);var critter=critters.spawn(context.definition().parameters().getOrDefault("critter","GLIMMERFLY"),player.getUniqueId());View view=new View(context.session().instanceId(),player.getUniqueId(),critter.instanceId(),display,hitbox);byEncounter.put(view.encounterId,view);byHitbox.put(hitbox.getUniqueId(),view);context.resources().own(()->remove(view.encounterId));player.sendMessage(Component.text("A Glimmerfly hovers nearby. Approach and interact to observe it.",NamedTextColor.GOLD));}
	@EventHandler(ignoreCancelled=true) public void interact(PlayerInteractEntityEvent event){View view=byHitbox.get(event.getRightClicked().getUniqueId());if(view==null||!view.owner.equals(event.getPlayer().getUniqueId()))return;event.setCancelled(true);var instance=critters.find(view.critterId).orElse(null);if(instance==null)return;if(instance.state()!=CritterState.SETTLED){critters.approach(view.critterId,false);critters.observe(view.critterId);event.getPlayer().sendMessage(Component.text("You study its rhythm. It settles—interact once more to finish the hunt.",NamedTextColor.YELLOW));return;}critters.capture(view.critterId);encounters.get().complete(view.encounterId);event.getPlayer().sendMessage(Component.text("Glimmerfly documented and released.",NamedTextColor.GREEN));}
	private void remove(UUID encounterId){View view=byEncounter.remove(encounterId);if(view==null)return;byHitbox.remove(view.hitbox.getUniqueId());critters.find(view.critterId).ifPresent(value->critters.escape(view.critterId));view.display.remove();view.hitbox.remove();}
	@Override public void close(){for(UUID id:new ArrayList<>(byEncounter.keySet()))remove(id);HandlerList.unregisterAll(this);}
	private record View(UUID encounterId,UUID owner,UUID critterId,ItemDisplay display,Interaction hitbox){}
	private record PluginHandle(org.bukkit.plugin.Plugin value){}
}
