package org.tomdang.critter.runtime;
import org.tomdang.critter.definition.*;import org.tomdang.gameplay.event.GameplayEventBus;import org.tomdang.gameplay.event.type.*;import java.time.*;import java.util.*;
/** Server-independent hunting state machine. Presentations translate world input into these transitions. */
public final class CritterRuntimeService{
	private final CritterRegistry definitions;private final GameplayEventBus events;private final Clock clock;private final Map<UUID,CritterInstance> active=new LinkedHashMap<>();public CritterRuntimeService(CritterRegistry definitions,GameplayEventBus events){this(definitions,events,Clock.systemUTC());}CritterRuntimeService(CritterRegistry definitions,GameplayEventBus events,Clock clock){this.definitions=definitions;this.events=events;this.clock=clock;}
	public CritterInstance spawn(String critterId,UUID owner){var value=new CritterInstance(UUID.randomUUID(),definitions.require(critterId).id(),owner,CritterState.UNAWARE,0,clock.instant());active.put(value.instanceId(),value);return value;}public Optional<CritterInstance> find(UUID id){return Optional.ofNullable(active.get(id));}public Collection<CritterInstance> active(){return List.copyOf(active.values());}
	public CritterInstance approach(UUID id,boolean movingQuickly){var value=require(id);if(value.state().terminal())return value;var definition=definitions.require(value.definitionId());if(movingQuickly&&value.relocations()<definition.hunting().maximumRelocations())return replace(value,CritterState.FLEEING,value.relocations()+1);if(movingQuickly)return escape(id);return replace(value,value.state()==CritterState.UNAWARE?CritterState.CURIOUS:CritterState.SETTLED,value.relocations());}
	public CritterInstance observe(UUID id){var value=require(id);events.publish(new CritterObserved(value.ownerId(),value.definitionId()));return replace(value,CritterState.SETTLED,value.relocations());}
	public CritterInstance capture(UUID id){var value=require(id);if(value.state()!=CritterState.SETTLED)throw new IllegalStateException("Critter is not in a capture window");events.publish(new CritterCaptured(value.ownerId(),value.definitionId()));var result=replace(value,CritterState.CAPTURED,value.relocations());active.remove(id);return result;}
	public CritterInstance escape(UUID id){var result=replace(require(id),CritterState.ESCAPED,require(id).relocations());active.remove(id);return result;}public void removeOwnedBy(UUID player){active.values().removeIf(value->value.ownerId().equals(player));}
	private CritterInstance require(UUID id){var value=active.get(id);if(value==null)throw new IllegalArgumentException("Unknown critter instance "+id);return value;}private CritterInstance replace(CritterInstance value,CritterState state,int relocations){var next=new CritterInstance(value.instanceId(),value.definitionId(),value.ownerId(),state,relocations,clock.instant());active.put(next.instanceId(),next);return next;}
}
