package org.tomdang.entityai.core;
import org.tomdang.entityai.navigation.Navigator;import java.util.*;
public final class AiBrain {
	private final AiAgent agent;private final AiSensor sensor;private final Navigator navigator;private final List<AiGoal> goals;private final AiMemory memory=new AiMemory();private AiGoal activeGoal;private AiBehavior activeBehavior;private PerceptionSnapshot perception=PerceptionSnapshot.empty(0);private long nextSense;
	public AiBrain(AiAgent agent,AiSensor sensor,Navigator navigator,List<AiGoal> goals){if(agent==null||sensor==null||navigator==null||goals==null||goals.isEmpty())throw new IllegalArgumentException("AI brain is incomplete");this.agent=agent;this.sensor=sensor;this.navigator=navigator;this.goals=goals.stream().sorted(Comparator.comparingInt(AiGoal::priority).reversed().thenComparing(AiGoal::id)).toList();if(this.goals.stream().map(AiGoal::id).distinct().count()!=this.goals.size())throw new IllegalArgumentException("AI goal ids must be unique");}
	public void tick(long tick){if(!agent.valid())return;if(tick>=nextSense){perception=sensor.sense(agent,tick);nextSense=tick+4;}AiContext context=new AiContext(agent,perception,memory,navigator,tick);AiGoal selected=goals.stream().filter(goal->goal.canStart(context)).findFirst().orElse(null);if(activeGoal!=null&&(!activeGoal.canContinue(context,activeBehavior)||(selected!=null&&selected.priority()>activeGoal.priority())))stop(context,true);if(activeGoal==null&&selected!=null){activeGoal=selected;activeBehavior=selected.start(context);}if(activeBehavior!=null&&activeBehavior.tick(context)!=AiBehaviorStatus.RUNNING)stop(context,false);}
	public void stop(){if(activeBehavior!=null)activeBehavior.stop(new AiContext(agent,perception,memory,navigator,perception.tick()),true);navigator.cancel(agent);activeGoal=null;activeBehavior=null;}
	private void stop(AiContext context,boolean interrupted){activeBehavior.stop(context,interrupted);navigator.cancel(agent);activeGoal=null;activeBehavior=null;}
	public Optional<String> activeGoal(){return activeGoal==null?Optional.empty():Optional.of(activeGoal.id());}public AiMemory memory(){return memory;}public AiAgent agent(){return agent;}
	public AiDiagnosticsSnapshot diagnostics(){return new AiDiagnosticsSnapshot(agent.id(),agent.type(),agent.worldId(),agent.position(),agent.home(),agent.capabilities(),goals.stream().map(goal->new AiGoalDiagnostics(goal.id(),goal.priority(),goal==activeGoal)).toList(),perception,memory.snapshot(),navigator.diagnostics(agent));}
}
