package org.tomdang.critter.configuration;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.YamlConfiguration;
import org.tomdang.critter.definition.*;
import java.io.*;import java.nio.charset.StandardCharsets;import java.time.Duration;import java.util.*;import org.tomdang.entityai.configuration.AiProfileLoader;
public final class CritterConfigurationLoader{
	public CritterDefinition load(InputStream input){if(input==null)throw new IllegalArgumentException("Critter input cannot be null");var yaml=YamlConfiguration.loadConfiguration(new InputStreamReader(input,StandardCharsets.UTF_8));var root=requireSection(yaml,"critter");var movement=requireSection(root,"movement");var hunting=requireSection(root,"hunting");var rewards=requireSection(root,"rewards");Map<String,CritterRewards.Drop> drops=new LinkedHashMap<>();var materials=rewards.getConfigurationSection("materials");if(materials!=null)for(String id:materials.getKeys(false)){var drop=requireSection(materials,id);drops.put(id.toUpperCase(Locale.ROOT),new CritterRewards.Drop(drop.getInt("minimum",1),drop.getInt("maximum",1),drop.getDouble("chance",1)));}
		return new CritterDefinition(text(root,"id"),text(root,"name"),text(root,"family").toUpperCase(Locale.ROOT),enumValue(root,"rarity",CritterRarity.class),upper(root.getStringList("habitats")),enums(root.getStringList("temperaments"),Temperament.class),new CritterMovement(enums(movement.getStringList("modes"),MovementType.class),movement.getDouble("wander-radius"),movement.getDouble("preferred-height"),movement.getDouble("speed"),Duration.ofSeconds(movement.getLong("rest-duration-seconds")),movement.getDouble("relocation-distance")),new CritterHunting(enums(hunting.getStringList("archetypes"),HuntingArchetype.class),hunting.getDouble("awareness-radius"),Duration.ofSeconds(hunting.getLong("capture-window-seconds")),hunting.getInt("maximum-relocations"),enumValue(hunting,"outcome",CaptureOutcome.class)),new CritterRewards(rewards.getLong("hunting-xp"),drops),root.getString("presentation","PLACEHOLDER").toUpperCase(Locale.ROOT),root.getString("journal-description",""),upper(root.getStringList("relations")),new AiProfileLoader().load(root.getConfigurationSection("ai")));
	}
	private ConfigurationSection requireSection(ConfigurationSection parent,String key){var value=parent.getConfigurationSection(key);if(value==null)throw new IllegalArgumentException("Missing "+key);return value;}private String text(ConfigurationSection section,String key){var value=section.getString(key);if(value==null||value.isBlank())throw new IllegalArgumentException("Missing "+key);return value;}private <E extends Enum<E>> E enumValue(ConfigurationSection section,String key,Class<E> type){return Enum.valueOf(type,text(section,key).toUpperCase(Locale.ROOT));}private <E extends Enum<E>> Set<E> enums(List<String> values,Class<E> type){var result=EnumSet.noneOf(type);for(String value:values)result.add(Enum.valueOf(type,value.toUpperCase(Locale.ROOT)));return result;}private Set<String> upper(List<String> values){var result=new LinkedHashSet<String>();for(String value:values)result.add(value.toUpperCase(Locale.ROOT));return result;}
}
